name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-check:
    name: drieam-reviewdog runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
